// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwDIajb0r5b5a3zX0mz-eaGdaJEhl9Ljk',
    appId: '1:347030663157:web:dd5cf73e873ac1023bbabc',
    messagingSenderId: '347030663157',
    projectId: 'mine-ms',
    authDomain: 'mine-ms.firebaseapp.com',
    storageBucket: 'mine-ms.appspot.com',
    measurementId: 'G-GMYSMSM3WL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi8m9_oir6LwkEmJNtpt5uor564WR_fxU',
    appId: '1:347030663157:android:7582a27f00013cd43bbabc',
    messagingSenderId: '347030663157',
    projectId: 'mine-ms',
    storageBucket: 'mine-ms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFDqm-sT_9iCkwC6JV0IKP9F695oHEiF4',
    appId: '1:347030663157:ios:65d699c2efea47d23bbabc',
    messagingSenderId: '347030663157',
    projectId: 'mine-ms',
    storageBucket: 'mine-ms.appspot.com',
    iosClientId: '347030663157-itog1lsm5hvq9pjln550nhm67r92of26.apps.googleusercontent.com',
    iosBundleId: 'com.ingemin.minems',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFDqm-sT_9iCkwC6JV0IKP9F695oHEiF4',
    appId: '1:347030663157:ios:65d699c2efea47d23bbabc',
    messagingSenderId: '347030663157',
    projectId: 'mine-ms',
    storageBucket: 'mine-ms.appspot.com',
    iosClientId: '347030663157-itog1lsm5hvq9pjln550nhm67r92of26.apps.googleusercontent.com',
    iosBundleId: 'com.ingemin.minems',
  );
}
